import numpy as np
database = {'Valuable drop:',
            'received a drop:',
            'You have a funny feeling like you’re being followed.',
            "You find a golden sceptre but dont have space to carry it. Clear some space in your pack and pick the sceptre up, if you want it…",
            'You have a funny feeling like you would have been followed...',
            'You feel something weird sneaking into your backpack.',
            'Your Scorpia kill count is: ',
            'Your Chaos Elemental kill count is: ',
            'New item added to your collection log: ',
            'Your mining level is now ',
            'Your smithing level is now ',
            'Your Woodcutting level is now ',
            'Your slayer level is now ',
            'Your hitpoints level is now ',
            'Your strength level is now ',
            'Your attack level is now ',
            'Your defence level is now ',
            'Your ranged level is now ',
            'Your prayer level is now ',
            'Your magic level is now ',
            'Your runecrafting level is now ',
            'Your construction level is now ',
            'Your agility level is now ',
            'Your thieving level is now ',
            'Your herblore level is now ',
            'Your hunter level is now ',
            'Your firemaking level is now ',
            'Your fishing level is now ',
            'Your farming level is now ',
            'Your cooking level is now ',
            'Your crafting level is now ',
            'Your Fletching level is now ',
            'You have completed all of the hard tasks in the Falador area.',
            "Your Seers' Village Rooftop lap count is: ",
            "Your Ardougne Rooftop lap count is: ",
            "Your Prifdinnas Agility Course lap count is: ",
            'You have opened the Grand Hallowed Coffin ',
            "Your Falador Rooftop lap count is: ",
            'Your herbiboar harvest count is: ',
            'Your completed Chambers of Xeric count is: ',
            'Your completed Theatre of Blood count is: ',
            'Your treasure is worth around ',
            'Your Barrows chest count is: ',
            'Your Giant Mole kill count is: ',
            'Your Kraken kill count is: ',
            'Your Grotesque Guardians kill count is: ',
            'Your Thermonuclear smoke devil kill count is: ',
            'Your Cerberus kill count is: ',
            'Your Abyssal Sire kill count is: ',
            'Your Alchemical Hydra kill count is: ',
            'Your Chaos Fanatic kill count is: ',
            'Your Crazy archaeologist kill count is: ',
            'Your King Black Dragon kill count is: ',
            "Your Vet'ion kill count is: ",
            'Your Venenatis kill count is: ',
            'Your Callisto kill count is: ',
            'Your Obor kill count is: ',
            'Your Bryophyta kill count is: ',
            'Your Mimic kill count is: ',
            'Your Hespori kill count is: ',
            'Your Zalcano kill count is: ',
            'Your Skotizo kill count is: ',
            'Your Deranged Archaeologist kill count is: ',
            'Your Dagannoth Supreme kill count is: ',
            'Your Dagannoth Rex kill count is: ',
            'Your Dagannoth Prime kill count is: ',
            'Your Sarachnis kill count is: ',
            'Your Kalphite Queen kill count is: ',
            "Your Kree'arra kill count is: ",
            'Your Commander Zilyana kill count is: ',
            'Your General Graardor kill count is: ',
            "Your K'ril Tsutsaroth kill count is: ",
            'Your Zulrah kill count is: ',
            'Your Vorkath kill count is: ',
            'Your Corporeal Beast kill count is: ',
            'Your Nightmare kill count is: ',
            "Your Phosani's Nightmare kill count is: ",
            'Your Corrupted Gauntlet completion count is: ',
            "I've completed all of the elite tasks in my Western achievement diary!",
            "I've completed all of the elite tasks in my Lumbridge achievement diary!",
            "I've completed all of the elite tasks in my Wilderness achievement diary!",
            "I've completed all of the elite tasks in my Ardougne achievement diary!",
            "I've completed all of the elite tasks in my Falador achievement diary!",
            "I've completed all of the elite tasks in my Varrock achievement diary!",
            "I've completed all of the elite tasks in my Kourend achievement diary!",
            "I've completed all of the elite tasks in my Desert achievement diary!",
            "I've completed all of the elite tasks in my Fremennik achievement diary!",
            "I've completed all of the elite tasks in my Karamja achievement diary!",
            "I've completed all of the elite tasks in my Morytania achievement diary!",
            "received a special loot from a raid: ",
            'has reached a total level of ',
            "has completed the Easy tier of the Combat Achievements!",
            "has completed the Medium tier of the Combat Achievements!",
            "has completed the Hard tier of the Combat Achievements!",
            "has completed the Elite tier of the Combat Achievements!",
            "has completed the Master tier of the Combat Achievements!",
            "has completed the Grandmaster tier of the Combat Achievements!",
            "You've completed all Combat Achievement tasks in the Easy Tier!",
            "You've completed all Combat Achievement tasks in the Medium Tier!",
            "You've completed all Combat Achievement tasks in the Hard Tier!",
            "You've completed all Combat Achievement tasks in the Elite Tier!",
            "You've completed all Combat Achievement tasks in the Master Tier!",
            "You've completed all Combat Achievement tasks in the Grandmaster Tier!",
            "Congratulations, you've completed an easy combat task: ",
            "Congratulations, you've completed an medium combat task: ",
            "Congratulations, you've completed an hard combat task: ",
            "Congratulations, you've completed an elite combat task: ",
            "Congratulations, you've completed a master combat task: ",
            "Congratulations, you've completed a grandmaster combat task: ",
            'The power of the fountain is transferred into an amulet'

            }
bosses = {  'Grotesque Guardians',
            'Kraken',
            'Thermonuclear smoke devil',
            }
insults = { "You didnt post an image dumbfuck",
            "Where's the image dipshit",
            "There's no image dickhead",
            "You didn't send an image needledick",
            "Please post an image and try again",
            "Learn how to attach an image fuckhead"

            }

motivation1 = [ "Champ,", "Fact:", "Everybody says", "Dang...", "Check it:", "Just saying...", "Superstar,", "Tiger,", "Self,", "Know this:", "News alert:", "Girl,", "Ace,", "Excuse me but", "Experts agree:", "In my opinion,", "Hear ye, hear ye:", "Okay, listen up:" ]
motivation2 = [ "the mere idea of you", "your soul", "your hair today", "everything you do", "your personal style", "every thought you have", "that sparkle in your eye", "your presence here", "what you got going on", "the essential you", "your life's journey", "that saucy personality", "your DNA", "that brain of yours", "your choice of attire", "the way you roll", "whatever your secret is", "all of y'all" ]
motivation3 = [ "has serious game,", "rains magic,", "deserves the Nobel Prize,", "raises the roof,", "breeds miracles,", "is paying off big time,", "shows mad skills,", "just shimmers,", "is a national treasure,", "gets the party hopping,", "is the next big thing,", "roars like a lion,", "is a rainbow factory,", "is made of diamonds,", "makes birds sing,", "should be taught in school,", "makes my world go 'round,", "is 100% legit," ]
motivation4 = [ "24/7.", "can I get an amen?", "and that's a fact.", "so treat yourself.", "you feel me?", "that's just science.", "would I lie?", "for reals.", "mic drop.", "you hidden gem.", "snuggle bear.", "period.", "can I get an amen?", "now let's dance", "high five.", "say it again!", "according to CNN.", "so get used to it." ]
